### ISSUE TITLE
Keep Golang in january :)

### ISSUE THREAD

**Issue by Im-Jinsu** [yoonjs741/Banosa_Project#1]
|  Date  |  Review  |
|---|---|
|  ✅ 2021-01-09  |  package 단위 폴더 구성하기, echo 활용하기 |
|  ❌ 2021-01-10  |    |
|  ✅ 2021-01-11  |  주석 작성  |
|  ❌ 2021-01-12  |    |
|  ❌ 2021-01-13  |  양꼬치 먹느라 커밋 몬함  |
|  ❌ 2021-01-14  |    |
|  ❌ 2021-01-15  |    |
|  ❌ 2021-01-16  |    |
|  ✅ 2021-01-17  |  어떤걸 더 수정해야할지 고민한듯 커밋  |
|  ❌ 2021-01-18  |    |
|  ❌ 2021-01-19  |    |
|  ❌ 2021-01-20  |    |
|  ✅ 2021-01-21  |  Log를 찍는 법에 대해 고민, 숙제 : log package 공부하기 |
|  ❌ 2021-01-22  |  깨톡캐톡 PASS  |
|  🥇 2021-01-23  |  소래포구까지 RUN, 커밋은 안함👿   |
|  ✅ 2021-01-24  |  log package 공부완료  |
|  ❌ 2021-01-25  |    |
|  ✅ 2021-01-26  |  저스트-주석쓰 🏃   |
|  ❌ 2021-01-27  |    |
|  ❌ 2021-01-28  |    |
|  ✅ 2021-01-29  |  쿼리로 받아 펙토리얼 구하는 Request/Response 작성  |
|  ❌ 2021-01-30  |    |
|  ❌ 2021-01-31  |    |

**Comment by yoonjs741** [comment]
2021-01 Keep GOLANG 챌린지 실패.

스스로에게 대단히 실망스럽다. 
2021-02 Keep GOLANG 챌린지는 위기감을 갖고 꼭 성공할 수 있도록 마음 다시 잡아야겠다.

"오늘 할일 내일로 미루지 말자." -벤자민 프랭클린-
