### ISSUE TITLE
Keep Golang in February :) 

### ISSUE THREAD

**Issue by yoonjs741** [yoonjs741/Banosa_Project#2]
|  Date  |  Review  |
|---|---|
|  ✅ 2021-02-01  |  GetFacto함수 입력/리턴 자료형 int로 변경. JSON 응답 컨트롤러 추가 🉑 |
|  ✅ 2021-02-02  |  fmt.Sprintf 를 다시 strconv.Itoa 로 변경. GetPrice 기능 초안 추가  |
|  ✅ 2021-02-03  | Pricing함수 추가. Value, Coupon쿼리 받아서 Price 반환   |
|  ✅ 2021-02-04  |  Graphql 요청 함수 공부.  |
|  ❌ 2021-02-05  |  Everyday Fish에서 한잔하고 FAIL🤦‍♂️  |
|  ✅ 2021-02-06  |  Graphql Test Code 추가, machinebox lib 만지작 만지작  |
|  ❌ 2021-02-07  |  모닝등산 후 쳐자느라 FAIL🤦‍♂️  |
|  ✅ 2021-02-08  |  Graphql Client 이것저것 만져봄   |
|  ✅ 2021-02-09  |  Graphql... lib쓸때랑 안쓸때 차이 비교해봄  |
|  ⬜ 2021-02-10  |    |
|  ⬜ 2021-02-11  |    |
|  ⬜ 2021-02-12  |    |
|  ⬜ 2021-02-13  |    |
|  ⬜ 2021-02-14  |    |
|  ⬜ 2021-02-15  |    |
|  ⬜ 2021-02-16  |    |
|  ⬜ 2021-02-17  |    |
|  ⬜ 2021-02-18  |    |
|  ⬜ 2021-02-19  |    |
|  ⬜ 2021-02-20  |    |
|  ⬜ 2021-02-21  |    |
|  ⬜ 2021-02-22  |    |
|  ⬜ 2021-02-23  |    |
|  ⬜ 2021-02-24  |    |
|  ⬜ 2021-02-25  |    |
|  ⬜ 2021-02-26  |    |
|  ⬜ 2021-02-27  |    |
|  ⬜ 2021-02-28  |    |

**Comment by Im-Jinsu** [comment]
Already started!! 👍

**Comment by Im-Jinsu** [comment]
Hey.. why didn't you commit

**Comment by yoonjs741** [comment]
Big problem in February commit project. Such a shame.

TRY HARD
NO GIVE  UP
